set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(LINUX_ARCH_NAME "x86_64-unknown-linux-gnu")
set(CMAKE_SIZEOF_VOID_P 8)

set(CLANG_TOOLCHAIN_ROOT "${TOOLCHAIN_ROOT}/${LINUX_ARCH_NAME}")
set(CLANG_TOOLCHAIN_BIN "${CLANG_TOOLCHAIN_ROOT}/bin")
set(CPACK_PACKAGE_ARCHITECTURE "${LINUX_ARCH_NAME}")

set(CMAKE_C_COMPILER "${CLANG_TOOLCHAIN_BIN}/clang.exe")
set(CMAKE_C_COMPILER_TARGET ${LINUX_ARCH_NAME})
set(CMAKE_CXX_COMPILER "${CLANG_TOOLCHAIN_BIN}/clang++.exe")
set(CMAKE_CXX_COMPILER_TARGET ${LINUX_ARCH_NAME})
set(CMAKE_ASM_COMPILER_TARGET ${LINUX_ARCH_NAME})

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_HAVE_PTHREAD_CREATE true)

set(CMAKE_FIND_ROOT_PATH ${CLANG_TOOLCHAIN_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_SYSROOT "${CLANG_TOOLCHAIN_ROOT}")
set(CMAKE_C_FLAGS_INIT   " --target=${LINUX_ARCH_NAME} --sysroot=${CLANG_TOOLCHAIN_ROOT} -fno-math-errno -fno-rtti -fno-exceptions -fdiagnostics-format=msvc -funwind-tables -gdwarf-3")
set(FLAGS_DEBUG          " -O0 -g -D_DEBUG")
set(FLAGS_MINSIZEREL     " -Os -DNDEBUG")
set(FLAGS_RELEASE        " -O3 -DNDEBUG")
set(FLAGS_RELWITHDEBINFO " -O3 -g -D_DEBUG")

#set(CMAKE_SYSTEM_INCLUDE_PATH "")
#set(CMAKE_INCLUDE_PATH "")